### ISSUE TITLE
Openui5 add new version 1.50.5

### ISSUE THREAD

**Issue by rkreddy9999** [webjars/openui5#51]
1.50.5  is the latest stable release.
Please add in webjars.

**Comment by ManuelB** [comment]
I need this aswell :-)

**Comment by ManuelB** [comment]
1.50.6 was released 8 days ago and a release of 1.48.14 would be awesome aswell.

**Comment by jamesward** [comment]
The download for `https://openui5.hana.ondemand.com/downloads/openui5-sdk-1.48.14.zip` wasn't there.  So I'm just releasing `1.50.6`.

**Comment by rkreddy9999** [comment]
Hello,
We  1.50.5 version only. I could not see that 1.50.6 version in OpenUI5 officical website. So please add 1.50.5

**Comment by jamesward** [comment]
Whoops.  That was a typo.  I'd released `1.50.5` yesterday.

**Comment by ManuelB** [comment]
Just for completeness 1.50.6. was now correctly deployed:
https://github.com/SAP/openui5/issues/1787

**Comment by jamesward** [comment]
That has been deployed.
