### ISSUE TITLE
Please release 1.52.5

### ISSUE THREAD

**Issue by ManuelB** [webjars/openui5#52]
The new long term release is 1.52.5

This is described here:

https://openui5.hana.ondemand.com/versionoverview.html

**Comment by ManuelB** [comment]
Is it possible to get release permission for webjars on central? I can do these releases on my own :-)

Further @jamesward do you have an amazon gift list, patreon or collective account? I would like to thank you for your work that you are doing here.

**Comment by jamesward** [comment]
Thanks @ManuelB.  This will be released shortly.

We don't have a good way for others to deploy Classic WebJars.  You can do that with NPM / Bower WebJars but I'm not sure if that is an option with this library.

Your support is the only gift I need!  Thank you!

**Comment by ManuelB** [comment]
@jamesward  thanks a lot for your super fast support.

![You are awesome](http://i0.kym-cdn.com/photos/images/newsfeed/000/066/552/whos-awesome.jpg)
