### ISSUE TITLE
Please Release Version: 1.54.6

### ISSUE THREAD

**Issue by ramakrishnareddymandhala** [webjars/openui5#54]
please add latest version 1.54.6 ASAP.

please do needful

**Comment by jamesward** [comment]
Verson `1.54.6` doesn't exist but I'll release the latest `1.54.7` shortly.

**Comment by ramakrishnareddymandhala** [comment]
I have seen open ui5 version 1.54.7 version doesn't exist, How you will release?
please find attached screen shot
![image](https://user-images.githubusercontent.com/6904939/42365022-93f90df2-80fd-11e8-847d-d508c3d7cce9.png)

**Comment by jamesward** [comment]
Where did you get that list from?  This is where I found the latest (`1.54.7`): https://openui5.org/download.html
